language: python
python:
  - '3.7'
env: MINICONDA="https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" PYTHONVER="3.7"
install:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - ./.ci_support/travis_setup_pygge.sh ${MINICONDA} ${PYTHONVER}
script:
  - coverage run -m unittest discover tests
  - coverage combine